language: node_js

env:
  global:
    - secure: "uydPaIshcRKRMqQtpe+o0kWv865U3u9TiJkpxpbs/q8qV092fkPxr7DA2ENsxck3VKpoFsVQwuRd0rxa2XbE/bMCe8W8OHsmPPYgOoTOogFqCPdRNcvk5NsfWbW6grOn2KqbzE+To3wV2a5ZVOIMcjShTgvrl+C5Bo89DI3iDL4sWGkveb+17T+oB/guN5GvXguIvn+foAeeo28p3VH8nGau6COGY7jjWAjNBpEtvzTkB058wOx/y9dqi+qQ1s8EgHrkI43LgJ6KUbsxgwCOMtngh0QTv/4rPcQnIQvTkEkFe+6F5YjOLwrAc0y4HWUlANpbNhQxMKz0uoI/DU7SxnNQziQtJifnvmjOUkRjdmiW6R6ycLezx47WbVVxHRAIDa766E0+BZMwMjkNrJu+AgB1IIDRZuyb12bT5kI+ElvJCYI7IUSw4w7PbxApsGizI+s9r6lPJG/iCLB1OuCr8zfQwWBWDSd9EvaxfQyb6YTsXTHisfrvnqahimLbbNF/SvhaEgyN/55fHO6FGe3NiNaDKQbtzIhk28L7vnZsXzeBlLCFzVb5knGUXmt/HMolU8zauCD4ZHb9DkT8i4cbbLjtZdzihnuQ2qE8ng19IpirI7r50C9Pu8GUqa8UoMP98WOItXYmUJ6zwk8h/AnQi5FaUQu9jOolvHHhA4pTXag="

install:
- npm install

before_script:

script:
- npm test

after_success:
- npm run dist
- bash deploy.bash
